## Basic Operations

In [ ]:
print("hello world") #to print something
name= "shiva"        #to define a variable
print(name)          #to print a defined variable

#Arithmetic Operations
print("2+3=",2+3)   #addition
print("2-3=", 2-3)   #subtraction
print("2*3=", 2*3)  #multiplication
print("2/3=",2/3)   #division
print("2**3=", 2**3) #power
print("2%3=", 2%3)  #remainder
print("5%2=", 5%2)
print("5//2=", 5//2) #rounds up the value of the quotient

'''order of operation matters'''
print ("4+2-3*2=",4+2-3*2 )
print("(4+2-3)*2=",(4+2-3)*2) 

## Variables and Types

In [1]:
x = 'My name is shiva'
type(x)

str

In [2]:
x= "my name is golu"
type(x) #str, or string: a type to represent text. You can use single or double quotes to build a string.

str

In [5]:
x= True
type(x) #bool, or boolean: a type to represent logical values. Can only be True or False (the capitalization is important!).

bool

##### The operators in Python behave differently for diffferent data types-

In [7]:
2+3 # Here the + operators adds two different integers

5

In [11]:
x = 'ab'+'cd'  # Here the same + operator pastes two strings together
print(x)

abcd


##### Converting data types


In [13]:
# Definition of savings and result
savings = 100

# Fix the printout
print("I started with $" + str(savings) + " and now have $" + str(result) + ". Awesome!")

# Definition of pi_string
pi_string = "3.1415926"

# Convert pi_string into float: pi_float
pi_float = float(pi_string)
type(pi_float)

I started with $100 and now have $194.87171000000012. Awesome!


float

## Lists
##### To create(use) many data points. A list is a collection of values, which may be of different data types such as float, int, str 

##### you can also have lists of lists

In [1]:
#Create simple list
list = ['john','chintu']
list

['john', 'chintu']

In [49]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas
areas = [hall,kit,liv,bed,bath]

# Print areas
print(areas)




[11.25, 18.0, 20.0, 10.75, 9.5]


In [46]:
[1 + 2, "a" * 5, 3] #interesting list

[3, 'aaaaa', 3]

##### Lists of Lists


In [52]:
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom",bed],
         ['bathroom',bath]]
print(house)

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]


##### List Subsetting **use square brackets for creating and calling lists


In [2]:
family = ['john','chintu','shiv','sid','sam']
family[1] #use square

'chintu'

In [64]:
family[2]

'golu'

##### List Slicing

In [3]:
family[1:4] #[start(inclusive) : End(exclusive)]

['chintu', 'shiv', 'sid']

In [4]:
family[:4]

['john', 'chintu', 'shiv', 'sid']

In [5]:
family[2:]

['shiv', 'sid', 'sam']

In [6]:
family[:]

['john', 'chintu', 'shiv', 'sid', 'sam']

##### Subsetting lists of lists

In [93]:
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom",bed],
         ['bathroom',bath]]
house[2][0]

'living room'

In [79]:
house[-1][1]

9.5

##### List Manipulation

In [7]:
fam=['radha','vish','ram','fizzy','sanvi']
fam_ext= family+fam               #Adding to Lists
fam_ext                  

['john',
 'chintu',
 'shiv',
 'sid',
 'sam',
 'radha',
 'vish',
 'ram',
 'fizzy',
 'sanvi']

In [8]:
family[0]= 'piggy' #Replacing an element of the list
family

['piggy', 'chintu', 'shiv', 'sid', 'sam']

In [9]:
family[0:2] = ['randy','amy'] #Repalcing more than one element in the list
family

['randy', 'amy', 'shiv', 'sid', 'sam']

In [94]:
del(house[1:3])
house

[['hallway', 11.25], ['bedroom', 10.75], ['bathroom', 9.5]]

In [17]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]
print(areas)


['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]


## Looping

In [1]:
#to print something n times

for x in range(0,10):
    print(x)

print('\n')

for x in range(0,10):
    print(x, end=" ")

    #end="" - same line with no space between
    #end=" " - same line with a space between
    #end="\n"- enters the next line

print("\n")

#example 1
list=['bananas','potatoes','apples','mangoes']
for y in list:
    print(y)
print('\n')

list=['bananas','potatoes','apples','mangoes']
for y in range(0,4):
    print(list[y])
print('\n')
list=['bananas','potatoes','apples','mangoes']
for y in range(0,4):
    print(list[2])

print('\n')

#example 2
for x in [1,6,1,4]:
    print(x)
print('\n')

#lists in lists

numlist= [[1,2,3],[10,20,30],[100,200,300],[1000,2000,3000]]
for x in range(0,4):
    for y in range(0,3):
        print(numlist[x][y])

        


0
1
2
3
4
5
6
7
8
9


0 1 2 3 4 5 6 7 8 9 

bananas
potatoes
apples
mangoes


bananas
potatoes
apples
mangoes


apples
apples
apples
apples


1
6
1
4


1
2
3
10
20
30
100
200
300
1000
2000
3000


## Functions

#### To store and Re-use

In [11]:
def greeting():
    print("hello")
    print("namaste")
print(2)
greeting()

2
hello
namaste


In [30]:
def greet(lang):
    if lang=='es':
        return 'hola'
    elif lang=='fr':
        return'bonjour'
    else:
        return'hello'
greet('es')
greet('')
print(greet('fr'), 'pedro')

bonjour pedro


In [12]:
def greet(lang):
    if lang=='es':
        print('hola')
    elif lang=='fr':
        print('bonjour')
    else:
        print('hello')
greet('es')

hola


In [20]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



In [1]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first+second

# Sort full in descending order: full_sorted
full_sorted=sorted(full,reverse=True)

# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


In [2]:
room= "shiva"
room_up= room.upper()
print(room_up)

SHIVA


In [3]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))

# Print out how often 14.5 appears in areas
print(areas.count(14.5))


2
0


## Reading Files


In [ ]:
open() # returns a file handle
x = open(filename,mode) #mode= r - read; mode=w - write


In [31]:
x=open('readfile.txt')
print(x)

<_io.TextIOWrapper name='readfile.txt' mode='r' encoding='cp1252'>


# Packages


### Packages for Data science
##### numpy - To work with arrays
##### matplotlib - For data visualization
##### Scikit- learn - For Machine Learning

In [3]:
import numpy
numpy.array([1,2,3]) #more clear


array([1, 2, 3])

In [4]:
import numpy as np
np.array([1,2,3])  #shortcut

array([1, 2, 3])

In [11]:
from numpy import array
array([1,2,3])  #not preferred

array([1, 2, 3])

##### Working on Arrays using numpy

##### numpy arrays can contain only one type of data


In [34]:
height=[4.5,6.0,5.8,5.4,6.2,4.9]
weight=[50,58,70,65,84,75]
import numpy as np
height=np.array(height)
weight=np.array(weight)
print(weight)
print(height)
bmi=weight/height**2
print(bmi)
bmi>3


[50 58 70 65 84 75]
[ 4.5  6.   5.8  5.4  6.2  4.9]
[ 2.4691358   1.61111111  2.08085612  2.22908093  2.18522373  3.12369846]


array([False, False, False, False, False,  True], dtype=bool)

In [25]:
bmi[bmi>3]

array([ 3.12369846])

##### List Subsetting

In [35]:
print(height[2])
print(weight[0:3])


5.8
[50 58 70]


##### 2d-arrays

In [54]:
import numpy as np
a=[1,2,3,4,5]
b=[6,7,8,9,0]
x= np.array(a)
print(x)
y=np.array(b)
print(y)
z=[[1,2,3,4],[5,6,7,8]]  #two or more lists in one list
z=np.array(z)   # converting the lists of lists into arrays forms a 2-d matrix
print(z)
z.shape         # this gives the #rows and #columns present in the matrix

[1 2 3 4 5]
[6 7 8 9 0]
[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [45]:
z[0]

array([1, 2, 3, 4])

In [46]:
z[1][2]

7

In [47]:
z[1,2]

7

In [48]:
z[0:1]

array([[1, 2, 3, 4]])

In [58]:
z[:,1]  # to select only columns

array([2, 6])

In [59]:
z[1,:] #to select only rows

array([5, 6, 7, 8])

### Multidimensional Arrays

#### The general syntax for a slice is array[start:stop:step]

#### If stop comes before start in the array, then an array of length zero is returned

In [12]:
A=np.arange(9)
A


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
A[::1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
A[0:9:2]

array([0, 2, 4, 6, 8])

In [17]:
A[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [19]:
B = np.reshape(np.arange(9),(3,3))
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
B[0:2,::1]

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
B[0:2,::2]

array([[0, 2],
       [3, 5]])

In [23]:
B[0:2,::-1]

array([[2, 1, 0],
       [5, 4, 3]])